spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardaa
    username: boardaa
    password: boardaa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO # Spring 프레임워크 관련 로그를 INFO 레벨로 설정
    org.hibernate: INFO # Hibernate(JPA 구현체) 관련 로그를 INFO 레벨로 설정
    com.ohgiraffers.crud_back: DEBUG